### ISSUE TITLE
"Access is denied" Error 

### ISSUE THREAD

**Issue by kenns247** [kuanysh-nabiyev/RenameProjectVsExtension#17] opened 2018-01-18 16:48 UTC
![error](https://user-images.githubusercontent.com/22533398/35109749-d5ce8be4-fc3c-11e7-80bd-0312ab43df04.PNG)

Even after all possible files and folders that could be referencing the project are closed, I still get this error. 

I used the tool to successfully change the name of another project in the solution, (and it was awesome and worked really well, thank you!!) but now when I go to change a second project I am getting this error.

**Comment by kuanysh-nabiyev** [comment] 2018-01-18 18:30
@kenns247 Thank you. I am glad that it is helpful.

Please, check the permission to the folder. It should be at least write permission.

And look into the following issue https://github.com/kuanysh-nabiyev/RenameProjectVsExtension/issues/8. may be it will be helpful.

**Comment by kenns247** [comment] 2018-01-18 18:51
Uninstalling and reinstalling your extension did the trick! It appears to only work the first time after an install, so for every project name I wish to change I just need to uninstall and reinstall it again.

**Comment by kuanysh-nabiyev** [comment] 2018-01-18 20:05
@kenns247 very very strange for me. I am glad that you solved the problem

**Comment by moehoward** [comment] 2018-03-11 02:58
Is an uninstall and reinstall really the proper solution? I am getting the same exact issue using Visual Studio Enterprise 2017 Preview Version 15.6.1 Preview 1.0. It worked with previous versions but now it is not working at all.

PS - I loved this app when it was working!

**Comment by kuanysh-nabiyev** [comment] 2018-03-11 06:22
@moehoward is solution the same when you tried to rename with different VS versions?
please, attach image of exception stack trace (the exception can be different with the issue attached exception)

**Comment by moehoward** [comment] 2018-03-19 08:03
Yes. I get the same result with the latest Stable Community Edition.

![snapshot 1](https://user-images.githubusercontent.com/1805973/37583948-92aef646-2b21-11e8-800e-4ce8ef5806da.jpg)

**Comment by jerone** [comment] 2018-08-08 08:42
I'm having the same issue with Visual Studio Professional 2017 (15.7.6). For the solution (ASP.NET MVC) I'm trying I have full read&write permissions on every folder, still I get this exception. What else can I try?

**Comment by kuanysh-nabiyev** [comment] 2018-08-08 13:44
@jerone Honestly, I don't the reason of such exception. I cannot reproduce it. 
If it is possible you can send me sample project that reproduce the bug.

**Comment by jerone** [comment] 2018-08-08 20:29
@kuanysh-nabiyev I'm afraid i can't; it's an internal project. 
If i can find the time, I'll try to rename this project (to see if it's my environment).

**Comment by pmcstjean** [comment] 2018-09-16 18:10
Windows file explorer seems the culprit. Folder and file handles are preventing the project folder from being renamed. You could close it, stop using it or kill the handles manually with a tool like Sysinternal Handle.

**Comment by pmcstjean** [comment] 2018-09-16 18:44
May I suggest disabling VS feedback program too. For some reason it locks some files and stay forever running as perfwatson2.exe
  https://stackoverflow.com/questions/42662444/how-to-disable-perfwatson2-exe-from-visual-studio-2017

**Closed as completed** 2019-12-25 07:20 UTC
